### ISSUE TITLE
'pipenv install' broke 

### ISSUE THREAD

**Issue by PPION** [neurotechcenter/BCpy2000#2]
Hi, I run the `pipenv install` at a win10 computer but showing the following error.
My `python` version is 3.7.1 and use 2020.8.13 `pipenv`. 
Is the `Pipfile` or `Pipfile.lock` not fitting the latest `pipenv`?

> Traceback (most recent call last):
  File "d:\anaconda\lib\site-packages\pipenv\project.py", line 567, in _parse_pipfile
    return tomlkit.parse(contents)
  File "d:\anaconda\lib\site-packages\pipenv\vendor\tomlkit\api.py", line 49, in parse
    return Parser(string).parse()
  File "d:\anaconda\lib\site-packages\pipenv\vendor\tomlkit\parser.py", line 132, in parse
    item = self._parse_item()
  File "d:\anaconda\lib\site-packages\pipenv\vendor\tomlkit\parser.py", line 295, in _parse_item
    return self._parse_key_value(True)
  File "d:\anaconda\lib\site-packages\pipenv\vendor\tomlkit\parser.py", line 380, in _parse_key_value
    val = self._parse_value()
  File "d:\anaconda\lib\site-packages\pipenv\vendor\tomlkit\parser.py", line 517, in _parse_value
    return self._parse_array()
  File "d:\anaconda\lib\site-packages\pipenv\vendor\tomlkit\parser.py", line 663, in _parse_array
    raise self.parse_error(UnexpectedCharError, self._current)
tomlkit.exceptions.UnexpectedCharError: Unexpected character: 's' at line 1 col 6

>During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "d:\anaconda\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "d:\anaconda\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "D:\anaconda\Scripts\pipenv.exe\__main__.py", line 7, in <module>
  File "d:\anaconda\lib\site-packages\pipenv\vendor\click\core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "d:\anaconda\lib\site-packages\pipenv\vendor\click\core.py", line 782, in main
    rv = self.invoke(ctx)
  File "d:\anaconda\lib\site-packages\pipenv\vendor\click\core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "d:\anaconda\lib\site-packages\pipenv\vendor\click\core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "d:\anaconda\lib\site-packages\pipenv\vendor\click\core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "d:\anaconda\lib\site-packages\pipenv\vendor\click\decorators.py", line 73, in new_func
    return ctx.invoke(f, obj, *args, **kwargs)
  File "d:\anaconda\lib\site-packages\pipenv\vendor\click\core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "d:\anaconda\lib\site-packages\pipenv\vendor\click\decorators.py", line 21, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "d:\anaconda\lib\site-packages\pipenv\cli\command.py", line 252, in install
    site_packages=state.site_packages
  File "d:\anaconda\lib\site-packages\pipenv\core.py", line 1928, in do_install
    site_packages=site_packages,
  File "d:\anaconda\lib\site-packages\pipenv\core.py", line 580, in ensure_project
    pypi_mirror=pypi_mirror,
  File "d:\anaconda\lib\site-packages\pipenv\core.py", line 498, in ensure_virtualenv
    python = ensure_python(three=three, python=python)
  File "d:\anaconda\lib\site-packages\pipenv\core.py", line 385, in ensure_python
    python = project.required_python_version
  File "d:\anaconda\lib\site-packages\pipenv\project.py", line 243, in required_python_version
    required = self.parsed_pipfile.get("requires", {}).get(
  File "d:\anaconda\lib\site-packages\pipenv\project.py", line 544, in parsed_pipfile
    parsed = self._parse_pipfile(contents)
  File "d:\anaconda\lib\site-packages\pipenv\project.py", line 571, in _parse_pipfile
    return toml.loads(contents)
  File "d:\anaconda\lib\site-packages\pipenv\vendor\toml\decoder.py", line 262, in loads
    original, i)
toml.decoder.TomlDecodeError: Found invalid character in key name: '['. Try quoting the key name. (line 1 column 5 char 4)

**Comment by nicklczk** [comment]
Currently trying to reproduce this error, it may be that the newer version of Pipenv has changed the installation process, or a mismatching of the Python version. If you look at the pipfile the environment requires Python version 3.6.8, I will try to replicate your results and update the codebase accordingly sometime this weekend. If you need a stable working version today you can find the python2 version at [http://bci2000.org/downloads/BCPy2000/Download.html](url).

**Comment by PPION** [comment]
> Currently trying to reproduce this error, it may be that the newer version of Pipenv has changed the installation process, or a mismatching of the Python version. If you look at the pipfile the environment requires Python version 3.6.8, I will try to replicate your results and update the codebase accordingly sometime this weekend. If you need a stable working version today you can find the python2 version at [http://bci2000.org/downloads/BCPy2000/Download.html](url).

Thanks for your response. I tried 3.6.8 `Python` again and outputed the same error. A `python3 BCPy2000` is still necessary for many `python3` dependencies. To solve this problem, I use a `python3` script to bind `full monty` temporarily.

**Comment by PengboFan** [comment]
I have the same problem.But I tried to change the PipFile (remove the pipe in the first line) and the installation worked fine. This is probably the pipenv version mismatch that caused the above problem.

**Comment by trzp** [comment]
Try to change the first line "Pipe [[source]]" to "[[source]]".

**Comment by nicklczk** [comment]
We have moved away from Pipenv for the time being. Please follow the new instructions for installation and use in our README or on our [Wiki page](https://www.bci2000.org/mediawiki/index.php/BCPy2000).
